# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://mrmaxguns.github.io'
baseurl: ''
title: 'Maxim R.'
description: |
  This is the official blog of mrmaxguns where technology, science, art, and
  aviation meet. I write about different topics that interest me, and want to
  share my knowledge with the world.
permalink: pretty
logo: "/assets/images/logo.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: Blog
  url: /blog/
- title: Categories
  url: /categories/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts, ideas, and tutorials"
    feature_text: |
      <h3 style="color:white">Welcome to my blog! Here you'll find all the
      latest posts</h3>
    feature_image: "/assets/images/patterns/geo_pattern.jpg"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
